edk2-porting/edk2-msm

README.md

Added a port guide and removed sony device from the list of supported devices.

Added port guide

---

.github/workflows/main.yml

[![CI](https://github.com/mnixry/edk2-sdm845/actions/workflows/main.yml/badge.svg)](https://github.com/mnixry/edk2-sdm845/actions/runs/711810864)

update github workflow file to support artifact uploading

---

sdm845Pkg/Devices/fajita.fdf
sdm845Pkg/Drivers/Op6tSlotDxe/LICENSE
sdm845Pkg/Drivers/Op6tSlotDxe/Op6tSlotDxe.inf
sdm845Pkg/Drivers/Op6tSlotDxe/README.md
sdm845Pkg/Drivers/Op6tSlotDxe/crc32.c
sdm845Pkg/Drivers/Op6tSlotDxe/crc32.h
sdm845Pkg/Drivers/Op6tSlotDxe/slot.c
sdm845Pkg/Drivers/Op6tSlotDxe/slot.h
sdm845Pkg/sdm845Pkg.dsc

Add new driver Op6tSlotDxe for OnePlus 6T (fajita) to support A/B slot.

add new driver Op6tSlotDxe for OnePlus 6T (fajita)

---

Dockerfile
README.md
docker-compose.yml

- It include Docker 
- updated readme.md
- please update readme-zh.md

Added Docker Support

---

sdm845Pkg/Devices/fajita-8g.dsc
sdm845Pkg/Devices/fajita.dsc
sdm845Pkg/Devices/fajita.fdf

Signed-off-by: BigfootACA <bigfoot@classfun.cn>
Signed-off-by: Perseus X <xperseus2021@gmail.com>

sdm845Pkg: Devices: add SimpleInitGUI support for fajita

---

build.sh

use cnpmjs instead of fastgit to avoid crashing

---

Platform/LG/sm8150/betalm.fdf.inc

Also disable hacked up i2c and dalsys and gpi

Betalm: enable sdccDxe

---

Platform/Xiaomi/sm8250/AcpiTables/alioth/ufs.asl

Just PRing a sm8250 common commit that I forgot to push

Enable UFS

---

Platform/LG/sm8150/betalm.dsc
Platform/LG/sm8150/betalm.fdf.inc

Fix crash on boot on Betalm
* [ X] Have you tested the change you are submitting?
* [ X] Is the commits history nice and clean?

Betalm: fix crash on boot

---

Platform/Xiaomi/sm8150/vayu.fdf.inc

Vayu: Update vayu.fdf.inc

---

Platform/Xiaomi/sm7150/surya.fdf.inc

Now it is recognized when you connect and disconnect the usb but neither the keyboard nor the mouse works
* [ x] Have you tested the change you are submitting?
* [ x] Is the commits history nice and clean?

Poco X3 NFC: Add initial support for USB in UEFI

---

Platform/Razer/sdm845/linus.fdf.inc

Add ButtonsDxe for linus
* [Y] Have you tested the change you are submitting?
* [Y] Is the commits history nice and clean?

sdm845:Razer-linus:Update linus.fdf.inc

---

Platform/Xiaomi/sdm845/equuleus.dsc

sdm845:Xiaomi-equuleus:Update equuleus.dsc

---

Platform/Qualcomm/sm7125/sm7125.dsc

Fogot to add one of the changes into the previous commit lol
This fixes the compile issue for miatoll

fixup! sm7125: Port ACPI patching code

---

Platform/Xiaomi/sm7150/surya.fdf.inc

there really isn't any change, i just put everything where it should be
* [y] Have you tested the change you are submitting?
* [y] Is the commits history nice and clean?

correct positions in uefi (surya)

---

build.sh

Accelerate the Generating Speed of Padding.bin
* [×] Have you tested the change you are submitting?
* [√] Is the commits history nice and clean?

Accelerate the Generating Speed of Padding.bin

---

Silicon/Qualcomm/sdm845/Library/SOCSmbiosInfoLib/SOCSmbiosInfo.c
Silicon/Qualcomm/sdm845/Library/SOCSmbiosInfoLib/SOCSmbiosInfoLib.inf
Silicon/Qualcomm/sdm845/sdm845.dec

* Signed-off-by: qaz6750 <2838632319@qq.com>
* Use pcd to update soc description 
* [Y] Have you tested the change you are submitting?
* [Y] Is the commits history nice and clean?

sdm845: SOCSmbiosInfoLib: Use pcd to update soc description

---

Platform/Essential/msm8998/Library/mata/PlatformMemoryMapLib/PlatformMemoryMapLib.c
Platform/Essential/msm8998/Library/mata/PlatformMemoryMapLib/PlatformMemoryMapLib.inf
Platform/Essential/msm8998/mata.dsc
Platform/Nubia/msm8998/Library/nx563j/PlatformMemoryMapLib/PlatformMemoryMapLib.c
Platform/Nubia/msm8998/Library/nx563j/PlatformMemoryMapLib/PlatformMemoryMapLib.inf
Platform/Nubia/msm8998/nx563j.dsc
Platform/Oneplus/msm8998/Library/cheeseburger/PlatformMemoryMapLib/PlatformMemoryMapLib.c
Platform/Oneplus/msm8998/Library/cheeseburger/PlatformMemoryMapLib/PlatformMemoryMapLib.inf
Platform/Oneplus/msm8998/Library/dumpling/PlatformMemoryMapLib/PlatformMemoryMapLib.c
Platform/Oneplus/msm8998/Library/dumpling/PlatformMemoryMapLib/PlatformMemoryMapLib.inf
Platform/Oneplus/msm8998/cheeseburger.dsc
Platform/Oneplus/msm8998/dumpling.dsc
Platform/Qualcomm/msm8998/msm8998.dsc
Platform/Xiaomi/msm8998/Library/sagit/PlatformMemoryMapLib/PlatformMemoryMapLib.c
Platform/Xiaomi/msm8998/Library/sagit/PlatformMemoryMapLib/PlatformMemoryMapLib.inf
Platform/Xiaomi/msm8998/sagit.dsc

* All : To add PlatformMemoryMapLib separately for each device
* After testing, it works well in oneplus5

[Improvement-WIP] To add PlatformMemoryMapLib separately for each msm8998 device

---

tools/BootShim/BootShim.S

Bootshim fix

---

build.sh

Update build.sh chinese submodule

---

.github/workflows/main.yml

Just a workflow change that adds Wine required for Beryllium image being compiled and both variations of it.

workflow: add beryllium (tianma, ebbg)

---

.github/workflows/main.yml

Fix the installation of wine
(don't ask how)

workflow: fixup wine installation

---

.github/workflows/installer.yml

* [Y] Have you tested the change you are submitting?
* [Y] Is the commits history nice and clean?

Update installer.yml // Add Xiaomi 13 Build

---

.github/workflows/installer.yml
Platform/Xiaomi/sm7325/lisa.dsc

Corrected the name of device (lisa) and added the device (lisa) to Actions
* [ Y ] Have you tested the change you are submitting?
* [ Y ] Is the commits history nice and clean?

Corrected the naming of the device and added device to actions

---

Platform/LG/sm8150/betalm.fdf.inc

Remove UsbPowerCtrlDxe from betalm

---

.github/workflows/main.yml

* [yes] Have you tested the change you are submitting?
* [yes] Is the commits history nice and clean?

workflow: add guacamoleb in main.yml
